compiler/typecheck/TcHsType.hs

Fix for issue #13 providing an error message on an attempted use of linear arrows in kind signatures.
Using the same test case as in the issue:
```
{-# LANGUAGE KindSignatures #-}
data NormalType :: * -> *
data LinType :: * ⊸ *
class NormalClass (t :: * -> *)
class LinClass (t :: * ⊸ *)
instance NormalClass LinType
instance LinClass NormalType
```
You now get an error:
```
linear_kinds.hs:3:17: error:
• Linear arrows disallowed in kinds: * ⊸ *
• In the kind ‘* ⊸ *’
|
3 | data LinType :: * ⊸ *
|                 ^^^^^
```
You don't get an error about the other improper use yet, but that changes if you remove the first site:
```
linear_kinds.hs:4:22: error:
• Linear arrows disallowed in kinds: * ⊸ *
• In the kind ‘* ⊸ *’
|
4 | class LinClass (t :: * ⊸ *)
|                      ^^^^^
```
If …

#13 Disallow linear arrows in kinds

---

compiler/hsSyn/HsTypes.hs

Previously, it showed normal arrows as `ω` in error messages.  I didn't make a bug report because I though it would be easiest to just fix it.

Fix function type display in error messages

---

compiler/coreSyn/CoreLint.hs

Fixes CatPairs test and probably many others.
Fixes #49

Don't discard usage information from RHS of let bound variables

---

compiler/basicTypes/Id.hs
compiler/basicTypes/Var.hs
compiler/deSugar/DsArrows.hs
compiler/deSugar/DsExpr.hs
compiler/deSugar/DsUtils.hs
compiler/deSugar/Match.hs
compiler/deSugar/Match.hs-boot
compiler/deSugar/MatchCon.hs
compiler/deSugar/MatchLit.hs
compiler/hsSyn/HsBinds.hs
compiler/hsSyn/HsExpr.hs
compiler/hsSyn/HsUtils.hs
compiler/typecheck/TcArrows.hs
compiler/typecheck/TcHsSyn.hs
compiler/typecheck/TcMatches.hs
compiler/typecheck/TcPatSyn.hs
ghc/GHCi/UI/Info.hs

When desugaring case expressions we sometimes invent new variables which
need to be scaled like source level case expressions. Storing this
weight allows us to perform this scaling appropiately.
This fixes test `T11339c` at least.

Keep track of weight in MatchGroup

---

compiler/stranal/WwLib.hs

As we are making a `case_w` we have to also have omega variables here.
This is highlighted by the new core lint check which checks that pattern
binders have the correct annotation on them.
This will have to be changed when it is refined later.

WW: Scale arg_tys by Omega

---

compiler/basicTypes/Var.hs
compiler/coreSyn/CoreLint.hs
compiler/deSugar/DsUtils.hs
testsuite/skip-tests.txt

There are three changes in these three commits which each fix a problem.
1. In `DsUtils` we have to scale the binders by the weight of the case. (See #82 for the tests this fixes)
2. `scaleVarBy` was needlessly partial, we so we fix that by performing a no-op in the case we don't have an `Id`
3. My complicated calculations in `lintCoreAlt` turned out to be wrong - surprise, surprise. We need to use `dataConRepArgTys` to properly account for data con wrappers but for some reason still deal explicitly with existentially bound variables.

Scale binders bound in a data con wrapper

---

.circleci/config.yml
compiler/deSugar/DsExpr.hs
compiler/deSugar/Match.hs
compiler/deSugar/Match.hs-boot
compiler/deSugar/MatchCon.hs
compiler/deSugar/MatchLit.hs
compiler/hsSyn/HsExpr.hs
compiler/typecheck/TcBinds.hs
compiler/typecheck/TcMatches.hs
compiler/typecheck/TcPat.hs

The binders were over-eagerly scaled. Generally by Omega. This PR fetches the multiplicities closer to the binders (for when new variables need to be created by the desugarer). It also avoids scaling variables whose multiplicity is already known (which would change a variable of multiplicity `p` (a variable) into `p * p` which is problematic).
This is overall a simplification, I think. In that it reduces the number of changed lines in the overall diff.
I tucked something about Circle CI. Because it felt too trivial to put in another PR.

Binder multiplicities in desugarer

---

compiler/coreSyn/CoreLint.hs
compiler/types/UsageEnv.hs

Was mistakenly summing the usage of alternatives, reverted to joining,
as it ought to

Linter: fix usage of case alternatives

---

compiler/deSugar/DsArrows.hs
compiler/deSugar/DsExpr.hs
compiler/deSugar/DsListComp.hs
compiler/deSugar/DsUtils.hs
compiler/deSugar/Match.hs
compiler/hsSyn/HsExpr.hs
compiler/hsSyn/HsUtils.hs
compiler/typecheck/TcHsSyn.hs
compiler/typecheck/TcMatches.hs

In
```haskell
do
pat <- rhs
body
```
If `pat` is not a variable, then the multiplicity was lost (that is,
for `(>>=) :: a :p-> (b :q-> c) :r-> d`, the renamed needs `q`) and it
would always be desugared to
```haskell
rhs >>= (\ x ::[ω] -> case x of pat -> body)
```
Which is ill-typed.

Do-notation: propagate pattern-multiplicity to the renamer

---

compiler/basicTypes/DataCon.hs
compiler/basicTypes/MkId.hs
compiler/coreSyn/CoreFVs.hs
compiler/coreSyn/CoreOpt.hs
compiler/iface/IfaceSyn.hs
compiler/iface/IfaceType.hs
compiler/typecheck/TcMType.hs
compiler/typecheck/TcTyDecls.hs
compiler/typecheck/TcType.hs
compiler/typecheck/TcValidity.hs
compiler/types/Coercion.hs
compiler/types/FamInstEnv.hs
compiler/types/TyCoRep.hs
compiler/types/Type.hs
compiler/types/Unify.hs

Don't push coercions through lambdas or application if they change the multiplicity. This is done, concretely, by checking whether the multiplicity component of the coercion is a reflexivity before pushing a coercion.

Fix coercions of arrow types

---

compiler/coreSyn/CorePrep.hs
testsuite/skip-tests.txt

This fixes the multiplicity of the lets generated by the CorePrep pass (which, in particular, is responsible for putting core expressions in administrative normal form).
I'll clean history before merge (and after merging #121 which it depends on).
I've noticed more CorePrep bugs in further files in linear-base. So there must still be bugs.
Works towards #117 .

CorePrep lets

---

compiler/basicTypes/Id.hs
compiler/basicTypes/MkId.hs
compiler/coreSyn/CoreArity.hs
compiler/coreSyn/CorePrep.hs
compiler/simplCore/SetLevels.hs
compiler/simplCore/SimplEnv.hs
compiler/simplCore/SimplMonad.hs
compiler/simplCore/SimplUtils.hs
compiler/simplCore/Simplify.hs
compiler/specialise/SpecConstr.hs
compiler/stranal/WwLib.hs
compiler/typecheck/TcRnMonad.hs
compiler/types/TyCoRep.hs
compiler/vectorise/Vectorise/Builtins/Initialise.hs
compiler/vectorise/Vectorise/Monad/Naming.hs

This PR reverts the changes which the alias-like binders of #128 have rendered obsolete.
This is not a pure revert, but should be close enough.

Revert obsoleted changes

---

.circleci/config.yml

I'm not too sure about this. It may have a significant cost in compilation time, which would be unfortunate.
But preserving the linter is really important for this PR. So I hacked something. It's really ugly too, but takes the advantage that the CI configuration is already heavily tweaked.
An alternative is to have two jobs in CI, one building the test, the other using `-dcore-lint` on the libraries.
At any rates, local tests suggest that the build passes the linter (!), but I'd like the CI to check from a clean state for me every time.
Green will close #122 .

Activate linter in the CI

---

compiler/basicTypes/DataCon.hs
compiler/basicTypes/MkId.hs
compiler/deSugar/Desugar.hs
compiler/iface/IfaceSyn.hs
compiler/simplCore/Simplify.hs
compiler/typecheck/ClsInst.hs
compiler/typecheck/Inst.hs
compiler/typecheck/TcInstDcls.hs

This is quite a bit more simpler, the constructors are never
manipulate by the user anyway, and it avoids having to track all the
the places where dictionaries are instantiated and insert the
appropriate multiplicity arguments throughout the code.

Type-class constructors have no wrappers

---

compiler/deSugar/DsExpr.hs

This was missed during merge; I'm not sure if there are any
consequences.

Fix a warning

---

compiler/iface/IfaceSyn.hs
compiler/iface/IfaceType.hs
testsuite/tests/ghci/scripts/all.T
testsuite/tests/linear/should_run/LinearGhci.script
testsuite/tests/linear/should_run/LinearGhci.stdout
testsuite/tests/linear/should_run/Makefile
testsuite/tests/linear/should_run/all.T

Hide multiplicities when printing constructors

---

compiler/types/Type.hs

`nonDetCmpTypeX` is supposed to be a linear order (for example, it is used as an argument to `sortBy`). 
It was returning "greater" when one multiplicity was not a submultiplicity of another. This feels wrong, since that would make 0 < 1 < 0. (I don't have an example code where this goes wrong.)

Don't use submultMaybe to compare types

---

compiler/basicTypes/ConLike.hs
compiler/basicTypes/DataCon.hs-boot
compiler/basicTypes/Multiplicity.hs
compiler/basicTypes/Var.hs
compiler/basicTypes/Var.hs-boot
compiler/coreSyn/CoreMap.hs
compiler/deSugar/MatchCon.hs
compiler/prelude/TysWiredIn.hs-boot
compiler/typecheck/TcMatches.hs
compiler/typecheck/TcPat.hs
compiler/types/TyCoRep.hs
compiler/types/TyCoRep.hs-boot
compiler/types/Type.hs-boot
compiler/types/Unify.hs
compiler/types/UsageEnv.hs

Refs #276
Not moving `basicTypes/Multiplicity.hs` yet to avoid conflicts.
This turned out to be harder than expected: I wanted to resolve new import cycles by adding `Multiplicity.hs-boot`, but it's not possible to have pattern synonyms in hs-boot files (https://ghc.haskell.org/trac/ghc/ticket/13322).

Instantiate GMult to Type

---

compiler/basicTypes/Multiplicity.hs
compiler/prelude/PrelNames.hs
compiler/prelude/TysWiredIn.hs
compiler/prelude/TysWiredIn.hs-boot
compiler/types/TyCon.hs-boot
compiler/types/Type.hs-boot
libraries/ghc-prim/GHC/Types.hs

Refs #60.
Not working yet (#159 might help):
```
λ> comp :: (b -->.(p) c) -> (a -->. (q) b) -> a -->.(MultMul p q) c; comp f g x = f (g x)
<interactive>:3:76: error:
• Occurs check: cannot construct the infinite type: p ~ MultMul p q
arising from an application
```
The type from #212:
```data T a where MkT :: a -->.(p) T a```
no longer panics, but it gives ambiguity error, and its type looks weird:
```
λ> :type +v MkT
MkT
:: forall {p1 :: Multiplicity} {n :: Multiplicity} a
(p2 :: Multiplicity).
a -->.(MultMul n p1) T a
```

Multiplicity addition and multiplication families

---

.circleci/config.yml
compiler/types/OptCoercion.hs

Fixes #317.
We were ignoring multiplicity when optimizing function coercions. On the surface, this wouldn't cause trouble, but the optimizer handles `Sym co` by flipping the Boolean flag `sym`. By not having this call, coercions in multiplicity parameters were not flipped where they should have been.

Fix debug build

---

compiler/parser/Parser.y
testsuite/tests/linear/should_fail/LinearNoExt.stderr

Before:
```
TestL.hs:3:6: error: Enable LinearTypes to allow linear functions
|
3 | f :: (Bool->Bool) ->. (Bool->Bool , Bool->Bool)
|      ^^^^^^^^^^^^
```
After:
```
TestL.hs:3:19: error: Enable LinearTypes to allow linear functions
|
3 | f :: (Bool->Bool) ->. (Bool->Bool , Bool->Bool)
|                   ^^^
```

Fix location in 'Enable LinearTypes' message

---

compiler/typecheck/TcBinds.hs
compiler/typecheck/TcEnv.hs
compiler/typecheck/TcMatches.hs
testsuite/tests/linear/should_fail/Linear13.hs
testsuite/tests/linear/should_fail/Linear13.stderr

This moves the let-binder scaling to `tcMatchesFun`, atseems to be used by all the different paths which typecheck let bindings.
(I also snuck in a small debug facility)
This fixes #329

Fix lets with signatures

---

compiler/basicTypes/DataCon.hs
compiler/hsSyn/HsPat.hs

Refs #335
With this change, we have only one assertion failure caused by linear types: https://circleci.com/gh/tweag/ghc/3582 (additionally, there are assertion failures on master that are fixed in https://gitlab.haskell.org/ghc/ghc/merge_requests/716).
(I don't know why this is not causing trouble on master.)

Fix assertion failures with unboxed tuples

---

compiler/typecheck/TcBinds.hs

The minimal failing example was 
```
f x = g x
g x = f x
```

Fix recursive bindings without signatures

---

compiler/coreSyn/CoreLint.hs
compiler/types/Multiplicity.hs

This fixes, in particular, the issue with wrappers with strict
arguments, where the multiplicity of the argument was squared, as far
as the linter was concerned.

Fix usage of variables in linter

---

compiler/simplCore/Simplify.hs

Fixes
```haskell
{-# LANGUAGE  NoImplicitPrelude, BangPatterns #-}
module Test where
import GHC.Base
import GHC.Num
data  Ratio a = R !a
properFraction      :: (Num a, Num b) => (a -> (a, Integer)) -> Ratio a -> (b, Ratio a)
properFraction quotRem (R x) = let (q, t) = quotRem x in (fromInteger t, R (q+q))
ceiling :: (Num b, Num a) => (a -> (a, Integer)) -> (Ratio a -> a -> Bool) -> Ratio a -> (b, Bool)
ceiling quotRem e x = let !z = 0 in case properFraction quotRem x of (n, r) -> (n,  r `e` z)
```
See #335 .

Don't create non-alias lets in case-of-known-constructor

---

compiler/typecheck/TcBinds.hs

Fixes desugaring of:
```haskell
module Test where
b :: Bool
Just b = Nothing
```

Fix spurious aliases in case expressions

---

compiler/typecheck/TcUnify.hs
compiler/types/Multiplicity.hs
testsuite/tests/linear/should_compile/OldList.hs

Multiplicity multiplication now defaults to Omega.
This fixes the Core Lint issue for OldList; the old code fails to compile.

Remove the a*b <= c rule

---

compiler/simplCore/Simplify.hs

Fixes the `formatRealFloatAlt` in #335 .

 Scale binders in the fusing case continuation case-of-case instance 

---

compiler/typecheck/TcArrows.hs
compiler/typecheck/TcBinds.hs
compiler/typecheck/TcEnv.hs
compiler/typecheck/TcMatches.hs
compiler/typecheck/TcRnDriver.hs
compiler/typecheck/TcRnTypes.hs
compiler/typecheck/TcRules.hs

Previously, we were calling `tcSubMult` in `tc_extend_local_env`, which is called from many places.
However, it turns out that linearity checking is relevant only from one call site, `tcExtendIdEnv1`; this is the only function that could take non-Omega `ATcId`s. This significantly simplifies the logic, there are less modified functions in the final diff. Furthermore, `tcExtendIdEnv1` is called only from three places, and they can all be modified to take wrappers. This clears the obstacle for the plan of leaving wrappers in places that require multiplicity coercions.
One disadvantage is that `deleteUE` is called less often. I'm not sure whether this is a big problem.

Simplify linearity checking in TcEnv

---

.circleci/config.yml

xlarge is no longer freely available.
This is flaky; it succeeds sometimes, fails sometimes.

Workaround CircleCI limit

---

.buildkite/pipeline.yml

The flavor should be set before the instruction which loads the
corresponding settings file is executed.

Fix flavor selection
