- README.md
Contains instructions for both stack+Docker integration, as well as building from source.
> Add new README with build instructions for the fork

- README.md
Add getting-started information, explanation of errors from the linearity checker, as well as common pitfalls etc.
> Add usage documentation to README

- linear-tests/anf.hs
The problem here is in `prepareRhs` but is not fixed yet.
> Add a test for #50

- compiler/types/Coercion.hs
- linear-tests/Iden.hs
- testsuite/skip-tests.txt
Fixes #44 
The long road to find the one place to change continues.
> Use varWeight in mkPiCo

- .gitmodules
- compiler/basicTypes/Id.hs
- compiler/basicTypes/Var.hs
- compiler/coreSyn/CoreFVs.hs
- compiler/coreSyn/CoreOpt.hs
- compiler/coreSyn/CoreSubst.hs
- compiler/deSugar/DsBinds.hs
- compiler/deSugar/Match.hs
- compiler/simplCore/SimplEnv.hs
- compiler/typecheck/TcEvidence.hs
- compiler/typecheck/TcExpr.hs
- compiler/typecheck/TcHsSyn.hs
- compiler/typecheck/TcMType.hs
- compiler/typecheck/TcPat.hs
- compiler/typecheck/TcType.hs
- compiler/typecheck/TcUnify.hs
- compiler/types/TyCoRep.hs
- compiler/types/Type.hs
- libraries/base/Data/OldList.hs
- linear-tests/TupSection.hs
- testsuite/skip-tests.txt
This PR reverts the changes I had to make to several submodules and the associated fixes that had to be made to fix the fall out.
> Remove ETA reduction hacks from submodules

- compiler/simplCore/SimplEnv.hs
- compiler/simplCore/SimplUtils.hs
- compiler/simplCore/Simplify.hs
I don't know what, exactly, solved the issue I was observing on linear-base: I simply hunted occurrences of `Omega` in the simplifier, and finally got an error in another pass. So I must have solved something. At any rate, everything here is correctness improvements.
Works toward #117 .
> More caring about linearity in the simplifier

- libraries/base/GHC/Base.hs
> Restore a rewrite rule

- compiler/typecheck/TcPat.hs
> Disallow non-unrestricted @-patterns

- compiler/coreSyn/CoreOpt.hs
> Restore fast path in pushCoDataCon

- compiler/deSugar/DsBinds.hs
- compiler/deSugar/Match.hs
- compiler/typecheck/TcEvidence.hs
- compiler/typecheck/TcExpr.hs
- compiler/typecheck/TcHsSyn.hs
- compiler/typecheck/TcPat.hs
- compiler/typecheck/TcUnify.hs
It didn't actually make much sense.
Fixes #105. Fixes #107.
> Remove weight-wrapping argument in `WpFun`

- libraries/base/Data/OldList.hs
Introduced in d63c66ffa1c57c486a8ffe757c78cf4d19055d0c .
Finish fixing #97
> Revert workaround

- compiler/basicTypes/DataCon.hs-boot
- compiler/basicTypes/MkId.hs
- compiler/basicTypes/Weight.hs
- compiler/coreSyn/CoreMap.hs
- compiler/coreSyn/CoreSyn.hs
- compiler/coreSyn/CoreUtils.hs
- compiler/deSugar/DsBinds.hs
- compiler/deSugar/Match.hs-boot
- compiler/hsSyn/HsExpr.hs
- compiler/hsSyn/HsTypes.hs
- compiler/iface/IfaceSyn.hs
- compiler/iface/IfaceType.hs
- compiler/iface/LoadIface.hs
- compiler/typecheck/TcEnv.hs
- compiler/typecheck/TcErrors.hs
- compiler/typecheck/TcExpr.hs-boot
- compiler/typecheck/TcHsSyn.hs
- compiler/typecheck/TcHsType.hs
- compiler/typecheck/TcInteract.hs
- compiler/typecheck/TcPat.hs
- compiler/typecheck/TcTyClsDecls.hs
- compiler/typecheck/TcTyDecls.hs
- compiler/typecheck/TcType.hs
- compiler/typecheck/TcUnify.hs
- compiler/types/Coercion.hs-boot
- compiler/types/TyCoRep.hs
- compiler/types/TyCon.hs
- compiler/types/Type.hs
- compiler/types/Unify.hs
- compiler/types/UsageEnv.hs
Refs #93 
This fixes most, but not all, warnings.
> Fix -Wall warnings

- libraries/base/Data/Typeable/Internal.hs
- testsuite/skip-tests.txt
- testsuite/tests/typecheck/should_run/T14236.stdout
> Fix Typeable decomposition

- compiler/basicTypes/DataCon.hs
- compiler/basicTypes/MkId.hs
- compiler/basicTypes/Multiplicity.hs
- compiler/coreSyn/CoreArity.hs
- compiler/coreSyn/CoreUtils.hs
- compiler/deSugar/DsGRHSs.hs
- compiler/deSugar/DsMeta.hs
- compiler/hsSyn/Convert.hs
- compiler/simplCore/Exitify.hs
- compiler/simplCore/SimplUtils.hs
- compiler/simplStg/StgLiftLams/LiftM.hs
- compiler/typecheck/TcPatSyn.hs
- compiler/typecheck/TcSimplify.hs
- compiler/typecheck/TcSplice.hs
- compiler/types/Coercion.hs
- compiler/types/TyCoRep.hs
- compiler/types/Type.hs
> Address the last TODO comments

- compiler/types/TyCoRep.hs
I don't have any example that shows the previous code was wrong, but it feels wrong.
> tidyType: also tidy multiplicities

- compiler/basicTypes/Multiplicity.hs
- compiler/basicTypes/Var.hs
- compiler/coreSyn/CoreLint.hs
- compiler/coreSyn/CoreUtils.hs
- compiler/types/UsageEnv.hs
In my opinion, the extra convenience is not worth losing the ability to grep.
> Remove instance Num (GMult a)

- compiler/basicTypes/Multiplicity.hs
- compiler/types/FamInstEnv.hs
- compiler/types/Type.hs
> Look at multiplicity when flattening and in seqType

- compiler/typecheck/TcBinds.hs
- compiler/typecheck/TcEnv.hs
- compiler/typecheck/TcExpr.hs
- compiler/typecheck/TcPatSyn.hs
- compiler/typecheck/TcRnDriver.hs
- compiler/typecheck/TcRnTypes.hs
- compiler/typecheck/TcSplice.hs
- compiler/typecheck/TcTyClsDecls.hs
> Remove unused multiplicities from TcTypeEnv

- compiler/typecheck/TcForeign.hs
- compiler/types/Coercion.hs
- compiler/types/TyCon.hs
- libraries/base/GHC/Ptr.hs
- libraries/ghc-prim/GHC/Types.hs
Fixes #195.
This means we are lifting the restriction described in Note [FFI type roles] and can remove it.
> Make multiplicity parameter to functions nominal

- testsuite/tests/haddock/haddock_testsuite/all.T
> Fix haddock test and mark one as broken

- compiler/simplCore/SimplUtils.hs
- compiler/simplCore/Simplify.hs
This reverts part of #164 and fixes Lint for test T10694
> Restore hole scaling code

- compiler/simplCore/Simplify.hs
Don't know if it solves anything we observed. But this is most certainly something we must do.
> Scale case-floats in case-of-known constructors

- compiler/basicTypes/DataCon.hs
- compiler/basicTypes/MkId.hs
The first commit is a small independent refactoring.
> Disable assertion failing in T2334A

- compiler/prelude/PrelNames.hs
- compiler/prelude/TysWiredIn.hs
- compiler/prelude/TysWiredIn.hs-boot
- compiler/types/Multiplicity.hs
- libraries/ghc-prim/GHC/Types.hs
Not used after the change to `mkMulMul`
> Remove MultMul for now

- docs/users_guide/glasgow_exts.rst
> Add documentation

- compiler/deSugar/Match.hs
- compiler/hsSyn/HsPat.hs
As suggested at https://gitlab.haskell.org/ghc/ghc/merge_requests/980
> Move the unboxed tuple assertion to Match

- compiler/typecheck/TcUnify.hs
All error messages stay the same.
> Use unifyType in tcEqMult

- compiler/coreSyn/CoreLint.hs
- compiler/deSugar/DsBinds.hs
- compiler/typecheck/TcEnv.hs
- compiler/typecheck/TcEvidence.hs
- compiler/typecheck/TcExpr.hs
- compiler/typecheck/TcHsSyn.hs
- compiler/typecheck/TcPat.hs
- compiler/typecheck/TcUnify.hs
- compiler/typecheck/TcUnify.hs-boot
- compiler/types/Multiplicity.hs
- testsuite/tests/linear/should_fail/Linear1.stderr
- testsuite/tests/linear/should_fail/Linear11.stderr
- testsuite/tests/linear/should_fail/Linear13.stderr
- testsuite/tests/linear/should_fail/Linear17.stderr
- testsuite/tests/linear/should_fail/Linear2.stderr
- testsuite/tests/linear/should_fail/Linear5.stderr
- testsuite/tests/linear/should_fail/Linear7.stderr
- testsuite/tests/linear/should_fail/Linear9.stderr
- testsuite/tests/linear/should_fail/LinearAsPat.stderr
- testsuite/tests/linear/should_fail/LinearConfusedDollar.stderr
- testsuite/tests/linear/should_fail/LinearErrOrigin.stderr
- testsuite/tests/linear/should_fail/LinearLazyPat.stderr
- testsuite/tests/linear/should_fail/LinearLet.stderr
- testsuite/tests/linear/should_fail/LinearPatSyn.stderr
- testsuite/tests/linear/should_fail/LinearPolyType.stderr
- testsuite/tests/linear/should_fail/LinearRecordUpdate.stderr
- testsuite/tests/linear/should_fail/LinearSeq.stderr
- testsuite/tests/linear/should_fail/LinearVar.stderr
- testsuite/tests/linear/should_fail/LinearViewPattern.stderr
> Use a wrapper to detect multiplicity coercions

- compiler/coreSyn/CoreLint.hs
- compiler/prelude/PrelNames.hs
- compiler/prelude/TysWiredIn.hs
- compiler/prelude/TysWiredIn.hs-boot
- compiler/typecheck/TcUnify.hs
- compiler/types/Multiplicity.hs
- libraries/ghc-prim/GHC/Types.hs
- testsuite/tests/linear/should_compile/OldList.hs
Fixes the second half of #380.
> Add MultMul family back

- compiler/basicTypes/DataCon.hs
- compiler/basicTypes/MkId.hs
- compiler/basicTypes/MkId.hs-boot
- compiler/basicTypes/Unique.hs
- compiler/prelude/KnownUniques.hs
- compiler/prelude/TysWiredIn.hs
- compiler/rename/RnTypes.hs
- compiler/typecheck/TcInstDcls.hs
> Revert changes in DataCon and MkId

- compiler/coreSyn/CoreLint.hs
- compiler/coreSyn/CoreUtils.hs
- compiler/typecheck/TcEnv.hs
- compiler/typecheck/TcEvidence.hs
- compiler/typecheck/TcExpr.hs
- compiler/typecheck/TcPat.hs
- compiler/typecheck/TcType.hs
- compiler/typecheck/TcUnify.hs
- compiler/types/Multiplicity.hs
- compiler/types/TyCoRep.hs
- compiler/types/UsageEnv.hs
A number respond to the gitlab review.
> A large bunch of comments

- .buildkite/pipeline.yml
- default.nix
- nix/fetch-tarball-with-override.nix
- nix/pins/ghcide-nix.src-json
- nix/pins/nixpkgs.src-json
- nix/update-pin.sh
> Use buildkite
